[line_break]
disabled = false

[time]
disabled = true

[directory]
disabled = false
fish_style_pwd_dir_length = 1
truncation_length = 5
truncate_to_repo = false

[memory_usage]
disabled = false
threshold = 75
symbol = ""
style = 'bold dimmed yellow'
format = '$symbol[$ram( | $swap)]($style) '

[git_branch]
format = "[$symbol $branch]($style) "
symbol = "î‚ "

[git_metrics]
disabled = false

[package]
format = '[$symbol$version]($style) '

[container]
format = "[ğŸ³]($style) "

[golang]
symbol = "î˜§ "
